#Multi-stage YAML pipeline demo.
name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

variables:
- group: terraform_binary  # variable containing Terraform information like the Terraform version
- name: backend_secret_file_id1 # secret file used by the Terraform init cmdlet
  value: 'backend-main-jdld-1.json'
- name: main_secret_file_id1 # secret file used by the Terraform plan and destroy cmdlet
  value: 'main-jdld-1.json'

resources:
  repositories:
    - repository: terraform # identifier (A-Z, a-z, 0-9, and underscore)
      type: github
      endpoint: JamesDLD  # name of the service connection to use (for non-Azure Repos types)
      name: JamesDLD/terraform

trigger:
  batch: true # when a build is running, the system waits until the build is completed
  branches:
    include:
      - feature/*
  paths:
    include:
    - AzureDevops-Introduction/*

stages:
- stage: Deployment
  jobs:
    # track deployments on the environment
  - deployment: Terraform_Apply
    pool:
      vmImage: 'Ubuntu-16.04'
    # creates an environment if it doesn’t exist
    environment: 'staging'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - script: echo Deployment job in the staging environment

          - task: DownloadSecureFile@1
            displayName: 'Download secure file $(backend_secret_file_id1)'
            inputs:
              secureFile: $(backend_secret_file_id1)

          - task: DownloadSecureFile@1
            displayName: 'Download secure file $(main_secret_file_id1)'
            inputs:
              secureFile: $(main_secret_file_id1)

          - task: TerraformInstaller@0
            displayName: 'Use Terraform $(terraform_version)'
            inputs:
              terraformVersion: $(terraform_version)

          - script: |
              terraform init -backend-config="./variable/backend-jdld.tfvars" -backend-config="$(Agent.TempDirectory)/$(backend_secret_file_id1)" -reconfigure
              terraform plan -var-file="./variable/main-jdld.tfvars" -var-file="$(Agent.TempDirectory)/$(main_secret_file_id1)" -out="./out_plan_file" -input=false 
              terraform apply "./out_plan_file"
            displayName: 'Terraform Apply'
            workingDirectory: './AzureDevops-Introduction/aks-k8s/'

- stage: Delivery
  jobs:
    # track deployments on the environment
  - deployment: Terraform_Destroy
    pool:
      vmImage: 'Ubuntu-16.04'
    # creates an environment if it doesn’t exist
    environment: 'production'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - script: echo Deployment job in the production environment

          - task: DownloadSecureFile@1
            displayName: 'Download secure file $(backend_secret_file_id1)'
            inputs:
              secureFile: $(backend_secret_file_id1)

          - task: DownloadSecureFile@1
            displayName: 'Download secure file $(main_secret_file_id1)'
            inputs:
              secureFile: $(main_secret_file_id1)

          - task: TerraformInstaller@0
            displayName: 'Use Terraform $(terraform_version)'
            inputs:
              terraformVersion: $(terraform_version)

          - script: |
              terraform init -backend-config="./variable/backend-jdld.tfvars" -backend-config="$(Agent.TempDirectory)/$(backend_secret_file_id1)" -reconfigure
              terraform destroy -var-file="./variable/main-jdld.tfvars" -var-file="$(Agent.TempDirectory)/$(main_secret_file_id1)" -auto-approve
            displayName: 'Terraform Destroy'
            workingDirectory: './AzureDevops-Introduction/aks-k8s/'