description: Multi-stage YAML pipeline demo.
name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

stages:
- stage: Build
  description: "kkk"
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - script: echo my first build job
- stage: Deploy
  jobs:
    # track deployments on the environment
  - deployment: DeployWeb
    pool:
      vmImage: 'Ubuntu-16.04'
    # creates an environment if it doesn’t exist
    environment: 'Demo1'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment

#https://devblogs.microsoft.com/devops/whats-new-with-azure-pipelines/
#Amazing, thanks for all those improvment! I was doing some test and I couldn't figuring out how to set through YAML a run trigger for new Artifacts or for a determined scheduled. Is this someting that we can do during the preview or is this planned?