#Multi-stage YAML pipeline demo.
name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

variables:
- group: terraform_binary  # variable containing Terraform information like the Terraform version
- name: backend_secret_file_id1 # secret file used by the Terraform init cmdlet
  value: 'backend-jdld.tfvars'
- name: main_secret_file_id1 # secret file used by the Terraform plan and destroy cmdlet
  value: 'main-jdld.tfvars'

resources:
  repositories:
    - repository: terraform # identifier (A-Z, a-z, 0-9, and underscore)
      type: github
      endpoint: JamesDLD  # name of the service connection to use (for non-Azure Repos types)
      name: JamesDLD/terraform

trigger:
  batch: true #when a build is running, the system waits until the build is completed
  branches:
    include:
      - feature/*
  paths:
    include:
    - AzureDevops-Introduction/*

stages:
- stage: Deployment
  jobs:
    # track deployments on the environment
  - deployment: Terraform_Apply
    pool:
      vmImage: 'Ubuntu-16.04'
    # creates an environment if it doesn’t exist
    environment: 'staging'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment in the staging environment
- stage: Delivery
  jobs:
    # track deployments on the environment
  - deployment: Terraform_Destroy
    pool:
      vmImage: 'Ubuntu-16.04'
    # creates an environment if it doesn’t exist
    environment: 'production'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - script: echo my second deployment in the production environment